### ISSUE TITLE
Colour issues

### ISSUE THREAD

**Issue by moggers87** [stucox/git-conflict#1]
[Your choice of diff options](https://github.com/stucox/git-conflict/blob/7a6d5f18192a424cf3995a0d7437a3d8827c0530/git-conflict#L64) will cause issues for red-green colourblind users.

Personally, I would just remove `--color-words`, but I guess it's a very useful feature if you can use it ☺

**Comment by stucox** [comment]
Maybe `--color-words` should be optional. Some people might want full line diffs anyway.

I could remove that and just pass any extra args through to `git diff` for those who want them:

```
git conflict path/to/file --color-words
```
